language: csharp
mono: none
dist: xenial
dotnet: 3.1
services:
  - postgresql
  - elasticsearch
addons:
  postgresql: "10"
install:
  - dotnet restore
before_script:
  - sleep 120
script:
  - dotnet build --configuration Release
  - dotnet test Tests/YY.EventLogExportAssistant.Core.Tests/YY.EventLogExportAssistant.Core.Tests.csproj
  - dotnet test Tests/YY.EventLogExportAssistant.PostgreSQL.Tests/YY.EventLogExportAssistant.PostgreSQL.Tests.csproj
  - dotnet test Tests/YY.EventLogExportAssistant.ElasticSearch.Tests/YY.EventLogExportAssistant.ElasticSearch.Tests.csproj
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./Scripts/deploy.sh && ./Scripts/deploy.sh $NUGET_API_KEY
  on:
    branch: master